### ISSUE TITLE
[Enhancement] Add Source Domain counts

### ISSUE THREAD

**Issue by Laicure** [Laicure/HostsX#3]
Add source domain count on generate for tracking

**Comment by StevenBlack** [comment]
I still don't have mine wired yet.  :-)

I'm thinking each file creation will leave its data behind in a local `.json` file, then a post-process will iterate that `.json` file, and update all the readme files.

**Comment by Laicure** [comment]
Oh.. I thought the count on your current hosts readme (the one on the tables) are the source count, silly me.

For the Win App fork, I think I'll just insert the count to the hosts file like:
_# <count> - <source>_
_# <count> - <source>_
_# <count> - <source>_

(I'll iterate per source file on generation start while doing the usual app string append.)

Though it might bloat the generated hosts file :/ or I'll add an option to toggle _add sources on generated hosts file_ thing.

Correct me if I'm wrong about those  ;)
Thanks for the heads-up :D

**Comment by Laicure** [comment]
Now Implemented at https://github.com/Laicure/HostsX/commit/74a73c74d264a62e4fab246dc1faf6f09723a85b
